### ISSUE TITLE
Service 'gostats' failed to build : Build failed

### ISSUE THREAD

**Issue by jf-freeman** [j-sims/idi#6]
When bash run.sh build I am getting the following error.
ERROR: failed to solve: process "/bin/sh -c mv /go/gostats/idic.toml /go/gostats/idic.toml.orig" did not complete successfully: exit code: 1
ERROR: Service 'gostats' failed to build : Build failed
started!

I have received this error 4 times and the /go/gostats directory is not there.  This is happening on Rocky Linux build.

**Comment by jf-freeman** [comment]
more information for you as well.
Starting...
Creating network "isidatainsights" with the default driver
Pulling influxdb (influxdb:1.8)...
1.8: Pulling from library/influxdb
Digest: sha256:1e547cd60dbbec0a6a58f95e978f6e929d2f54777cf83ca084a0f8bccaf5bb47
Status: Downloaded newer image for influxdb:1.8
Building gostats
[+] Building 1.1s (9/11)                                                                                                                                                                       docker:default
 => [internal] load .dockerignore                                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                                          0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                                     0.0s
 => => transferring dockerfile: 371B                                                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/golang:latest                                                                                                                                         0.5s
 => [1/7] FROM docker.io/library/golang@sha256:ec457a2fcd235259273428a24e09900c496d0c52207266f96a330062a01e3622                                                                                          0.0s
 => [internal] load build context                                                                                                                                                                        0.0s
 => => transferring context: 177B                                                                                                                                                                        0.0s
 => CACHED [2/7] RUN git clone https://github.com/tenortim/gostats.git                                                                                                                                   0.0s
 => CACHED [3/7] WORKDIR /go/gostats                                                                                                                                                                     0.0s
 => CACHED [4/7] RUN go build                                                                                                                                                                            0.0s
 => ERROR [5/7] RUN mv /go/gostats/idic.toml /go/gostats/idic.toml.orig                                                                                                                                  0.5s
------
 > [5/7] RUN mv /go/gostats/idic.toml /go/gostats/idic.toml.orig:
0.190 mv: cannot stat '/go/gostats/idic.toml': No such file or directory
------
Dockerfile:6
--------------------
   4 |     WORKDIR /go/gostats
   5 |     RUN go build
   6 | >>> RUN mv /go/gostats/idic.toml /go/gostats/idic.toml.orig
   7 |     ADD idic.toml /go/gostats/idic.toml.master
   8 |     ADD run.sh /go/gostats/run.sh
--------------------
ERROR: failed to solve: process "/bin/sh -c mv /go/gostats/idic.toml /go/gostats/idic.toml.orig" did not complete successfully: exit code: 1
ERROR: Service 'gostats' failed to build : Build failed
started!

**Comment by jbein** [comment]
Hello,
I believe the idic.toml is not within the gostats repository.
you have to remove or comment our the line in the gostats/Dockerfile. 
Works for me...

```# cat gostats/Dockerfile 
FROM golang

RUN git clone https://github.com/tenortim/gostats.git
WORKDIR /go/gostats
RUN go build
# RUN mv /go/gostats/idic.toml /go/gostats/idic.toml.orig
ADD idic.toml /go/gostats/idic.toml.master
ADD run.sh /go/gostats/run.sh
CMD [ "/bin/bash", "/go/gostats/run.sh" ]
```

Regards Jan

**Comment by j-sims** [comment]
fixed
